const students = [
    { no: 821, name: "Efe Mehmet Çalışkan", gender: "Erkek" },
    { no: 899, name: "Duru Göksu", gender: "Kız" },
    { no: 992, name: "Hasan Yılmaz Karataş", gender: "Erkek" },
    { no: 6112, name: "Deniz Gökdeniz", gender: "Kız" },
    { no: 6124, name: "Taha Peker", gender: "Erkek" },
    { no: 6153, name: "Ecrin Oktay", gender: "Kız" },
    { no: 6237, name: "Ali Güven Adlı", gender: "Erkek" },
    { no: 6238, name: "Sude Kök", gender: "Kız" },
    { no: 6239, name: "Kayra Kanşar", gender: "Kız" },
    { no: 6240, name: "Ayşe Sude Kılıç", gender: "Kız" },
    { no: 6241, name: "Meryem İhya Yeşil", gender: "Kız" },
    { no: 6242, name: "Eren İnce", gender: "Erkek" },
    { no: 6243, name: "Salih Mert", gender: "Erkek" },
    { no: 6244, name: "Zeynep Ravza Genç", gender: "Kız" },
    { no: 6245, name: "Gamze Güngör", gender: "Kız" },
    { no: 6246, name: "Rabia Yandım", gender: "Kız" },
    { no: 6247, name: "Abdullah Reşat Olğun", gender: "Erkek" },
    { no: 6248, name: "Derin Su Tekin", gender: "Kız" },
    { no: 6249, name: "Sudenaz Öztunç", gender: "Kız" },
    { no: 6250, name: "Doğukan Akan", gender: "Erkek" },
    { no: 6252, name: "Ülkü Beyza Albayrak", gender: "Kız" },
    { no: 6253, name: "Ecrin Evra Alkanalka", gender: "Kız" },
    { no: 6254, name: "Ali Bulut Gök", gender: "Erkek" },
    { no: 6256, name: "Azra Akfırat", gender: "Kız" },
    { no: 6259, name: "Nehir Karataş", gender: "Kız" },
    { no: 6261, name: "Sude Sena Acar", gender: "Kız" },
    { no: 6262, name: "Hayrünnisa Durmaz", gender: "Kız" },
    { no: 6263, name: "Emre Yumutğan", gender: "Erkek" },
    { no: 6264, name: "Berfin Göktaş", gender: "Kız" },
    { no: 6265, name: "Ahmet Doruk Aldı", gender: "Erkek" },
    { no: 6267, name: "Aylin Büyükkılıç", gender: "Kız" },
    { no: 6268, name: "Seval Tozar", gender: "Kız" },
    { no: 6269, name: "Yağmur Secer", gender: "Kız" },
    { no: 6270, name: "Nazar Erkan", gender: "Kız" },
    { no: 6325, name: "Mustafa Samet Çalışkan", gender: "Erkek" },
    { no: 6327, name: "Musab Kaya", gender: "Erkek" },
    { no: 6329, name: "Mehmet Furkan Geçgin", gender: "Erkek" },
    { no: 6332, name: "Efe Ateş Horuzum", gender: "Erkek" },
    { no: 6337, name: "İslam Eskeif", gender: "Erkek" },
    { no: 6345, name: "Ada Yiğitcan", gender: "Kız" },
    { no: 6353, name: "Metin Bertuğ Ölmez", gender: "Erkek" }
];
